### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by ghost** [theupweb/idea-lab#11]
Latest updates, fixes, and blog updates.

**Comment by ghost** [comment]
Should I create the newsletter form in footer or is there something else you are planning for.

**Comment by the-supernova** [comment]
I can help in sending user id to the mail service we use for newsletter(MailChimp for example), once they enroll for newsletter. I can use Express to interact with the API. From there we can design the email we want to send to all. Please let me know if there are other plans or I can help in any sort

**Comment by ghost** [comment]
That's great start working!

**Comment by gmnikhil** [comment]
Im interested.. what all form fields are required for the news letter? Should I create the backend from scratch?

**Comment by Priyanshu-official** [comment]
Yes

**Comment by gmnikhil** [comment]
Ok cool.. just mention the form fields.. and ill work on it

**Comment by Priyanshu-official** [comment]
@Nikcodes10 We will have for Now Email field only...
you are assigned for 2 Days
