### ISSUE TITLE
Idea Lab - Card component

### ISSUE THREAD

**Issue by ghost** [theupweb/idea-lab#12]
The card component will be rendered after you post an idea. This will be our main subcomponent in the whole application

**Comment by Priyanshu-official** [comment]
@JoshuaPoddoku I would like to work on this can you assign this task to me

**Comment by Priyanshu-official** [comment]
And can I use the framework?

**Comment by sanjay270899** [comment]
I want to work on this.

**Comment by ghost** [comment]
Sure make a PR
