### ISSUE TITLE
Add greetings action

### ISSUE THREAD

**Issue by musavveer** [theupweb/idea-lab#23]
I would like to add a Github Action for greeting new contributors with :
- New PR
- New Issue
Do assign it to me @JoshuaPoddoku

**Comment by Dhriti-Roy** [comment]
I would like to work on this . Kindly assign me it to me.

**Comment by ghost** [comment]
@musavveer and @Dhriti-Roy who's working?

**Comment by musavveer** [comment]
I'm working on it. 
I'll send the PR as earliest as possible.
