### ISSUE TITLE
Add Navbar Component

### ISSUE THREAD

**Issue by Priyanshu-official** [theupweb/idea-lab#27]
**Create a Navbar for Header in the component file**
Design Should be the Same as shown on [HomePage](https://github.com/theupweb/idea-lab#home-page-) (Check Readme File)

Framework used: Tailwind CSS
Tech stack: HTML, CSS, js, React

**Comment by sanjay270899** [comment]
I would Like to work on this.

**Comment by shrushti2000** [comment]
I would like to work on this issue

**Comment by Priyanshu-official** [comment]
@shrushti2000 I have assigned you for 2 days start working on 
If you have any issue let me Know

@sanjay270899 sorry she Already contact me for task will assign you another task
