### ISSUE TITLE
Improve Card component 

### ISSUE THREAD

**Issue by ghost** [theupweb/idea-lab#39]
- UI needs to be upgraded and minimized (CSS and Design)
- JSON data need to be passed using dummy data ( rendering component )
- Component should be rendered on the next page ( as the first one will be the landing page )

**Comment by sanjay270899** [comment]
@JoshuaPoddoku I would like to work on this.

**Comment by ghost** [comment]
Yes whenever you u make initial changes add a Snapshot here @sanjay270899

**Comment by sanjay270899** [comment]
@JoshuaPoddoku Can I get color hex-codes used in the card component?

**Comment by ghost** [comment]
You can use color picker chrome extension

**Comment by ghost** [comment]
@sanjay270899 , Find the style guide here: https://github.com/theupweb/idea-lab/blob/main/docs/style-guide.md

**Comment by sanjay270899** [comment]
@JoshuaPoddoku Is the structure of JSON for card components fine?

![image](https://user-images.githubusercontent.com/43892590/105302522-53679a80-5be1-11eb-92bc-48b81f9b48f2.png)

**Comment by ghost** [comment]
@sanjay270899 Yes.

**Comment by sanjay270899** [comment]
@JoshuaPoddoku 
![image](https://user-images.githubusercontent.com/43892590/105361799-179ff580-5c20-11eb-9611-912f27bd4d44.png)

**Comment by sanjay270899** [comment]
@JoshuaPoddoku Is it fine?

**Comment by ghost** [comment]
This is the design? or Implementation?

@sanjay270899 Looks great though

**Comment by sanjay270899** [comment]
@JoshuaPoddoku 
Implementation (code). I have implemented card design from scratch as Card.js component.

Should I send PR?

**Comment by ghost** [comment]
Yes definitely

**Comment by jatinjain001** [comment]
I would like to work on it please assign it to me if it is available
