### ISSUE TITLE
Adding splash screen

### ISSUE THREAD

**Issue by Vrushti24** [theupweb/idea-lab#41]
Adding splash screen can make your website look more attractive if u are okay with that can I work on this ??

**Comment by ghost** [comment]
@Vrushti24 can you send an example?

**Comment by Vrushti24** [comment]
Actually I have made it in flutter I don't have any sample in html css but
I can make the splash screen for this

**Comment by ghost** [comment]
Yes, send that one. I'll get some idea

**Comment by Vrushti24** [comment]
https://drive.google.com/file/d/1DP1pwjF2ZXpge2yJ_PeeOL1-1z34f127/view?usp=drivesdk

U can check this this one I made in flutter It makes the application look
more attractive

**Comment by ghost** [comment]
I have requested for the access.

**Comment by Vrushti24** [comment]
I have granted access so after the splash screen ur home page will be
visible .

**Comment by ghost** [comment]
Thanks @Vrushti24 , I have seen. Looks like a good to introduce the Project and Idea.


Go ahead.

**Comment by Vrushti24** [comment]
Glad you like it! I will start to work on it

**Comment by Vrushti24** [comment]
Please add DWOC tag and level tag thank u @JoshuaPoddoku

**Comment by ghost** [comment]
Yes sure! :)

**Comment by ghost** [comment]
@Vrushti24 , search for some good npm libraries for animation and splash screen


Let me share my list:
- http://leftstick.github.io/splash-screen
- https://animate.style/

**Comment by Vrushti24** [comment]
Thanks, I'll check it out.

**Comment by Vrushti24** [comment]
Hey I m facing error in vs code but when I run my code on notepad it works
any idea why is this happening?

**Comment by Vrushti24** [comment]
Hey it is working I have made one it's kind of ball bouncing and opening
the page with colours shall send u a video?

**Comment by Vrushti24** [comment]
https://drive.google.com/file/d/1EaRgTWcn5c9-LPgRcpJfck96r-OPmOiA/view?usp=drivesdk


I have made this after that a next page will be available if u like it I
can make a PR

**Comment by ghost** [comment]
We need to add Idea lab logo
what say?

**Comment by Vrushti24** [comment]
If u say so I will try that but did u like these??

**Comment by ghost** [comment]
Yes, I liked it :)

**Comment by Vrushti24** [comment]
Thats great i m trying to add the logo after that I will send u the video

**Comment by Vrushti24** [comment]
Hey I m not able include logo can u tell me how can do that ?

**Comment by ghost** [comment]
Can you send the code snippet ?

Use JSFiddle or Codepen to share

**Comment by Vrushti24** [comment]
https://drive.google.com/file/d/1FE73-H0eDFXD4nf5k7UzK_Pq12CmiWGk/view?usp=drivesdk


I have added logo in ball u check if u agree I will make a PR

**Comment by Vrushti24** [comment]
Sir I added actually did a really silly mistake sorry to bother u

**Comment by Vrushti24** [comment]
U can check I have send u email about that changes I made

**Comment by Vrushti24** [comment]
Sir any updates??

**Comment by Vrushti24** [comment]
Sir please check the PR #46 . Thank u  @JoshuaPoddoku
