### ISSUE TITLE
Adding Contributers name in the README file

### ISSUE THREAD

**Issue by Ayush7614** [theupweb/idea-lab#45]
![image](https://user-images.githubusercontent.com/67006255/105568826-7077a700-5d62-11eb-8fce-f0b3fdb46d6e.png)
Like this

**Comment by Ayush7614** [comment]
i have to work on the issue plss assign me

**Comment by Ayush7614** [comment]
@JoshuaPoddoku sir plss review it

**Comment by sanjay270899** [comment]
Thanks @Ayush7614 . But we do have a list of contributors in README.md
![image](https://user-images.githubusercontent.com/43892590/108178265-3f548180-712a-11eb-9c6d-9596170cd544.png)

**Comment by sanjay270899** [comment]
@Ayush7614 I agree that tabular looks better. But it takes more space, and we have to update it manually.

If you come with a solution where the list of contributors get update automatically then you can send a PR.

For now I am closing this issue.
