### ISSUE TITLE
Images are not responding.

### ISSUE THREAD

**Issue by musavveer** [theupweb/idea-lab#51]
The path for the images in Contributing file is not mentioned properly. I would like to fix it.
Please assign this to me @JoshuaPoddoku 
![image](https://user-images.githubusercontent.com/62888562/106158391-afb25780-61a9-11eb-9098-8b83e32161b3.png)

**Comment by ghost** [comment]
yes @musavveer you can procced and also revamp the readme file.

**Comment by Priyanshu-official** [comment]
@JoshuaPoddoku Everything Working fine in the file 
closing this issue
