### ISSUE TITLE
Contributing.md images not working.

### ISSUE THREAD

**Issue by LeeRenJie** [theupweb/idea-lab#54]
I was going through the contributing.md and found out that the images are not working:
<img width="639" alt="Screenshot 2021-02-05 202634" src="https://user-images.githubusercontent.com/67599130/107033672-9be1a380-67f0-11eb-9f0a-307f08c87bb5.png">

Also, most devs use GitHub in dark mode, therefore I would like to change these picture into dark mode version
<img width="657" alt="Screenshot 2021-02-05 202651" src="https://user-images.githubusercontent.com/67599130/107033749-b4ea5480-67f0-11eb-806c-6fd060a3ce79.png">

Maybe at the end, I could also add a gif to make it more fun
<img src="https://media.tenor.com/images/df8c44a1d20ab367fdcb21880985fd33/tenor.gif"   width="30%"/>

**Comment by LeeRenJie** [comment]
I'm sorry I just realized a similar issue created 8 days ago. Let me know if there are any other tweaks that could be made or I will delete this issue thanks! I am under DWOC.

**Comment by sanjay270899** [comment]
@LeeRenJie Go Ahead!
