### ISSUE TITLE
Add a contributor's table

### ISSUE THREAD

**Issue by himanshu007-creator** [theupweb/idea-lab#57]
I would like to work on this project under DWOC.

**Comment by sanjay270899** [comment]
Thanks @himanshu007-creator. But we do have a list of contributors in README.md
![image](https://user-images.githubusercontent.com/43892590/108178265-3f548180-712a-11eb-9c6d-9596170cd544.png)

**Comment by himanshu007-creator** [comment]
> Thanks @himanshu007-creator. But we do have a list of contributors in README.md
> ![image](https://user-images.githubusercontent.com/43892590/108178265-3f548180-712a-11eb-9c6d-9596170cd544.png)

yes, but i wanted to make it better, by including a link to commits of every member. like below
![2021-02-17 (3)](https://user-images.githubusercontent.com/65963997/108209300-252d9a00-7150-11eb-8017-5a91231c37c9.png)

**Comment by sanjay270899** [comment]
@himanshu007-creator I agree that tabular looks better. But it takes more space, and we have to update it manually.

If you come with a solution where the list of contributors get update automatically then you can send a PR.

**Comment by sanjay270899** [comment]
@himanshu007-creator Closing this issue. You can message here to reopen this issue if you want. Keep Contributing!
