### ISSUE TITLE
Duplicate  Main Idea, Contributors title section present in README.md

### ISSUE THREAD

**Issue by vismitap** [theupweb/idea-lab#60]
I noticed this after fixing #56 while scrolling down! 😓
![image](https://user-images.githubusercontent.com/47056243/108208809-87d26600-714f-11eb-87fb-1809bc6f6269.png)
![image](https://user-images.githubusercontent.com/47056243/108208867-96208200-714f-11eb-805b-fea0a18694ac.png)

I can fix the README.md. Please this to me!

**Comment by sanjay270899** [comment]
@vismitap Assigned!

Go through the whole README.md file, and make necessary changes according to you.
